# ========================================
#  لیست کامل حیوانات و مشخصاتشان
# ========================================

ANIMALS = {
    "dog": {
        "name": "سگ",
        "emoji": "🐕",
        "sound": "واق واق",
        "sound_keywords": ["واق واق", "واق‌واق", "واق"],
        "type": "omnivore",
        "description": "وفادارترین دوست انسان",
        "breeds": {
            "golden_retriever": {"name": "گلدن رتریور", "rarity": "common", "emoji": "🐕"},
            "husky": {"name": "هاسکی", "rarity": "rare", "emoji": "🐕‍🦺"},
            "poodle": {"name": "پودل", "rarity": "common", "emoji": "🐩"},
            "bulldog": {"name": "بولداگ", "rarity": "uncommon", "emoji": "🐕"},
            "german_shepherd": {"name": "ژرمن شپرد", "rarity": "uncommon", "emoji": "🐕"},
            "dalmatian": {"name": "دالماتین", "rarity": "rare", "emoji": "🐕"},
            "shiba_inu": {"name": "شیبا اینو", "rarity": "rare", "emoji": "🐕"},
            "chihuahua": {"name": "چیواوا", "rarity": "common", "emoji": "🐕"},
        },
        "food": ["غذای خشک", "غذای مرطوب", "تنقلات ویژه"],
        "habitat": "خانه با حیاط",
        "tricks": ["بشین", "بلند شو", "دستتو بده", "بیا اینجا"],
        "level_names": ["توله", "بچه", "جوان", "بالغ", "باتجربه", "قهرمان"],
    },
    "cat": {
        "name": "گربه",
        "emoji": "🐈",
        "sound": "میو میو",
        "sound_keywords": ["میو", "میو میو", "میاو"],
        "type": "carnivore",
        "description": "موجود مستقل و باهوش",
        "breeds": {
            "persian": {"name": "پرشین", "rarity": "common", "emoji": "🐈"},
            "siamese": {"name": "سیامی", "rarity": "rare", "emoji": "🐈"},
            "maine_coon": {"name": "مین کون", "rarity": "rare", "emoji": "🐈"},
            "british": {"name": "بریتیش", "rarity": "uncommon", "emoji": "🐈"},
            "scottish": {"name": "اسکاتیش", "rarity": "uncommon", "emoji": "🐈"},
            "bengal": {"name": "بنگال", "rarity": "epic", "emoji": "🐈"},
            "sphynx": {"name": "اسفنکس", "rarity": "epic", "emoji": "🐈‍⬛"},
        },
        "food": ["ماهی تازه", "غذای مرطوب", "غذای خشک"],
        "habitat": "آپارتمان راحت",
        "tricks": ["بشین", "بلند شو", "دستتو بده"],
        "level_names": ["بچه گربه", "گربه کوچیک", "گربه جوان", "گربه بالغ", "گربه باتجربه", "گربه افسانه‌ای"],
    },
    "rabbit": {
        "name": "خرگوش",
        "emoji": "🐇",
        "sound": "اوق اوق",
        "sound_keywords": ["اوق اوق", "اوق"],
        "type": "herbivore",
        "description": "موجود نرم و بامزه",
        "breeds": {
            "holland_lop": {"name": "هلند لاپ", "rarity": "common", "emoji": "🐇"},
            "angora": {"name": "آنگورا", "rarity": "rare", "emoji": "🐇"},
            "mini_rex": {"name": "مینی رکس", "rarity": "uncommon", "emoji": "🐇"},
            "dutch": {"name": "داچ", "rarity": "common", "emoji": "🐇"},
            "lionhead": {"name": "شیرسر", "rarity": "rare", "emoji": "🐇"},
        },
        "food": ["هویج", "علوفه", "تنقلات ویژه"],
        "habitat": "قفس بزرگ با علف",
        "tricks": ["بشین", "بپر"],
        "level_names": ["توله خرگوش", "خرگوش کوچیک", "خرگوش جوان", "خرگوش بالغ", "خرگوش پیر", "خرگوش افسانه‌ای"],
    },
    "hamster": {
        "name": "همستر",
        "emoji": "🐹",
        "sound": "ویک ویک",
        "sound_keywords": ["ویک ویک", "ویک"],
        "type": "omnivore",
        "description": "کوچولوی شیرین",
        "breeds": {
            "syrian": {"name": "سوری", "rarity": "common", "emoji": "🐹"},
            "dwarf": {"name": "ددوارف", "rarity": "uncommon", "emoji": "🐹"},
            "roborovski": {"name": "روبوروفسکی", "rarity": "rare", "emoji": "🐹"},
            "chinese": {"name": "چینی", "rarity": "uncommon", "emoji": "🐹"},
        },
        "food": ["غذای خشک", "تنقلات ویژه", "هویج"],
        "habitat": "قفس با چرخ",
        "tricks": ["بشین"],
        "level_names": ["توله همستر", "همستر کوچیک", "همستر جوان", "همستر بالغ", "همستر پیر", "همستر قهرمان"],
    },
    "parrot": {
        "name": "طوطی",
        "emoji": "🦜",
        "sound": "جیک جیک",
        "sound_keywords": ["جیک جیک", "جیک", "قار قار"],
        "type": "herbivore",
        "description": "زبان‌باز باهوش",
        "breeds": {
            "african_grey": {"name": "آفریقایی خاکستری", "rarity": "epic", "emoji": "🦜"},
            "macaw": {"name": "ماکائو", "rarity": "rare", "emoji": "🦜"},
            "cockatiel": {"name": "کاکاتیل", "rarity": "common", "emoji": "🦜"},
            "budgerigar": {"name": "مرغ عشق", "rarity": "common", "emoji": "🦜"},
            "lovebird": {"name": "جدایی‌ناپذیر", "rarity": "uncommon", "emoji": "🦜"},
        },
        "food": ["علوفه", "تنقلات ویژه", "غذای خشک"],
        "habitat": "قفس بزرگ با شاخه",
        "tricks": ["سلام کن", "ببوس", "برقص"],
        "level_names": ["جوجه طوطی", "طوطی کوچیک", "طوطی جوان", "طوطی بالغ", "طوطی باتجربه", "طوطی افسانه‌ای"],
    },
    "fish": {
        "name": "ماهی",
        "emoji": "🐠",
        "sound": "بلوب بلوب",
        "sound_keywords": ["بلوب بلوب", "بلوب"],
        "type": "carnivore",
        "description": "موجود آرامش‌بخش آبزی",
        "breeds": {
            "goldfish": {"name": "ماهی طلا", "rarity": "common", "emoji": "🐟"},
            "betta": {"name": "بتا", "rarity": "uncommon", "emoji": "🐠"},
            "clownfish": {"name": "دلقک‌ماهی", "rarity": "rare", "emoji": "🐠"},
            "guppy": {"name": "گاپی", "rarity": "common", "emoji": "🐟"},
            "angelfish": {"name": "ماهی فرشته", "rarity": "rare", "emoji": "🐟"},
        },
        "food": ["ماهی تازه", "غذای خشک"],
        "habitat": "آکواریوم",
        "tricks": [],
        "level_names": ["بچه ماهی", "ماهی کوچیک", "ماهی جوان", "ماهی بالغ", "ماهی پیر", "ماهی افسانه‌ای"],
    },
    "turtle": {
        "name": "لاک‌پشت",
        "emoji": "🐢",
        "sound": "هیسسس",
        "sound_keywords": ["هیسسس", "هیس"],
        "type": "herbivore",
        "description": "کند ولی پایدار",
        "breeds": {
            "red_ear": {"name": "گوش‌قرمز", "rarity": "common", "emoji": "🐢"},
            "box_turtle": {"name": "جعبه‌ای", "rarity": "uncommon", "emoji": "🐢"},
            "tortoise": {"name": "خشکی‌زی", "rarity": "rare", "emoji": "🐢"},
        },
        "food": ["علوفه", "هویج"],
        "habitat": "تراریوم",
        "tricks": [],
        "level_names": ["توله لاک‌پشت", "لاک‌پشت کوچیک", "لاک‌پشت جوان", "لاک‌پشت بالغ", "لاک‌پشت پیر", "لاک‌پشت افسانه‌ای"],
    },
    "cricket": {
        "name": "جیرجیرک",
        "emoji": "🦗",
        "sound": "جیر جیر",
        "sound_keywords": ["جیر جیر", "جیر"],
        "type": "omnivore",
        "description": "موجود شبانه پرسروصدا",
        "breeds": {
            "house": {"name": "خانگی", "rarity": "common", "emoji": "🦗"},
            "field": {"name": "صحرایی", "rarity": "uncommon", "emoji": "🦗"},
            "mole": {"name": "کور", "rarity": "rare", "emoji": "🦗"},
        },
        "food": ["غذای خشک", "علوفه"],
        "habitat": "تراریوم کوچیک",
        "tricks": [],
        "level_names": ["لارو جیرجیرک", "جیرجیرک کوچیک", "جیرجیرک جوان", "جیرجیرک بالغ", "جیرجیرک پیر", "جیرجیرک افسانه‌ای"],
    },
    "duck": {
        "name": "اردک",
        "emoji": "🦆",
        "sound": "واک واک",
        "sound_keywords": ["واک واک", "واک"],
        "type": "omnivore",
        "description": "پرنده آبی شیرین",
        "breeds": {
            "mallard": {"name": "وحشی", "rarity": "common", "emoji": "🦆"},
            "pekin": {"name": "پکین", "rarity": "common", "emoji": "🦆"},
            "mandarin": {"name": "ماندارین", "rarity": "rare", "emoji": "🦆"},
        },
        "food": ["علوفه", "غذای خشک"],
        "habitat": "استخر کوچیک",
        "tricks": ["بشین", "بپر"],
        "level_names": ["جوجه اردک", "اردک کوچیک", "اردک جوان", "اردک بالغ", "اردک پیر", "اردک افسانه‌ای"],
    },
    "frog": {
        "name": "قورباغه",
        "emoji": "🐸",
        "sound": "قور قور",
        "sound_keywords": ["قور قور", "قور"],
        "type": "carnivore",
        "description": "موجود آبخاکی بامزه",
        "breeds": {
            "green": {"name": "سبز", "rarity": "common", "emoji": "🐸"},
            "red_eye": {"name": "چشم‌قرمز", "rarity": "rare", "emoji": "🐸"},
            "poison_dart": {"name": "دارتی", "rarity": "epic", "emoji": "🐸"},
            "african_clawed": {"name": "چنگال‌آفریقایی", "rarity": "uncommon", "emoji": "🐸"},
        },
        "food": ["ماهی تازه", "غذای خشک"],
        "habitat": "تراریوم آبی",
        "tricks": ["بپر"],
        "level_names": ["قورباغه نوزاد", "قورباغه کوچیک", "قورباغه جوان", "قورباغه بالغ", "قورباغه پیر", "قورباغه افسانه‌ای"],
    },
    "cow": {
        "name": "گاو",
        "emoji": "🐄",
        "sound": "ماو ماو",
        "sound_keywords": ["ماو ماو", "ماو", "موو"],
        "type": "herbivore",
        "description": "حیوان مزرعه مفید",
        "breeds": {
            "holstein": {"name": "هلشتاین", "rarity": "common", "emoji": "🐄"},
            "jersey": {"name": "جرسی", "rarity": "uncommon", "emoji": "🐄"},
            "angus": {"name": "آنگوس", "rarity": "rare", "emoji": "🐄"},
        },
        "food": ["علوفه", "غذای خشک"],
        "habitat": "مزرعه بزرگ",
        "tricks": [],
        "level_names": ["گوساله", "گاو کوچیک", "گاو جوان", "گاو بالغ", "گاو پیر", "گاو افسانه‌ای"],
    },
    "sheep": {
        "name": "گوسفند",
        "emoji": "🐑",
        "sound": "بع بع",
        "sound_keywords": ["بع بع", "بع"],
        "type": "herbivore",
        "description": "حیوان پشمالوی آروم",
        "breeds": {
            "merino": {"name": "مرینو", "rarity": "common", "emoji": "🐑"},
            "lincoln": {"name": "لینکلن", "rarity": "uncommon", "emoji": "🐑"},
            "suffolk": {"name": "سافولک", "rarity": "rare", "emoji": "🐑"},
        },
        "food": ["علوفه", "غذای خشک"],
        "habitat": "مرتع",
        "tricks": [],
        "level_names": ["بره", "گوسفند کوچیک", "گوسفند جوان", "گوسفند بالغ", "گوسفند پیر", "گوسفند افسانه‌ای"],
    },
    "horse": {
        "name": "اسب",
        "emoji": "🐎",
        "sound": "شیهه",
        "sound_keywords": ["شیهه", "هیهی"],
        "type": "herbivore",
        "description": "حیوان باشکوه و قدرتمند",
        "breeds": {
            "arabian": {"name": "عربی", "rarity": "rare", "emoji": "🐎"},
            "thoroughbred": {"name": "خالص", "rarity": "epic", "emoji": "🐎"},
            "quarter": {"name": "کوارتر", "rarity": "uncommon", "emoji": "🐎"},
            "pony": {"name": "پونی", "rarity": "common", "emoji": "🐎"},
        },
        "food": ["علوفه", "غذای خشک"],
        "habitat": "اصطبل",
        "tricks": ["بشین", "بلند شو", "برقص"],
        "level_names": ["کره اسب", "اسب کوچیک", "اسب جوان", "اسب بالغ", "اسب باتجربه", "اسب افسانه‌ای"],
    },
}

COLORS = [
    "سفید", "مشکی", "قهوه‌ای", "طلایی", "نقره‌ای",
    "خاکستری", "نارنجی", "زرد", "دورنگ", "سه‌رنگ",
    "لکه‌دار", "راه‌راه", "کرمی", "قرمز", "آبی‌خاکستری"
]

GENDERS = ["نر", "ماده"]

RARITY_COLORS = {
    "common": "⚪",
    "uncommon": "🟢",
    "rare": "🔵",
    "epic": "🟣",
    "legendary": "🟡"
}

LEVEL_XP = {
    1: 0,
    2: 100,
    3: 300,
    4: 700,
    5: 1500,
    6: 3000,
    7: 5500,
    8: 9000,
    9: 14000,
    10: 21000,
}

WEATHER_TYPES = [
    {"type": "sunny", "name": "آفتابی", "emoji": "☀️", "effect": {"happiness": 5}},
    {"type": "rainy", "name": "بارانی", "emoji": "🌧️", "effect": {"health": -3}},
    {"type": "cloudy", "name": "ابری", "emoji": "☁️", "effect": {}},
    {"type": "windy", "name": "طوفانی", "emoji": "🌪️", "effect": {"happiness": -5, "health": -5}},
    {"type": "snowy", "name": "برفی", "emoji": "❄️", "effect": {"happiness": 3, "health": -2}},
    {"type": "hot", "name": "گرم", "emoji": "🌡️", "effect": {"hunger": -10, "health": -3}},
]
